### ISSUE TITLE
Only one package added to the list of translations

### ISSUE THREAD

**Issue by RamyTalal** [thepinecode/i18n#12]
I found an issue where if there are multiple packages only the last one is added to the list of translations.

**Comment by iamgergo** [comment]
@RamyTalal Hi!

Thanks, I'll take a look and let you know soon!

**Comment by iamgergo** [comment]
@RamyTalal So, thanks for the report!

Yes, I flattened the collection, so it overrode the translations with the last package's translations.
Now, it should be fixed. I released a new tag, so please update your package to get rid of the bug.

Thank you!

**Comment by RamyTalal** [comment]
@iamgergo Great! Thanks you :)
