### ISSUE TITLE
Select specific files

### ISSUE THREAD

**Issue by sardoj** [thepinecode/i18n#6]
Is it possible to add an option to select which files we want to use for translations?
For the moment i think translations of all files are added. It could be huge in a big project, and Google doesn't like very much when a page take time to load.
Any solution?
Thanks for your help.

**Comment by iamgergo** [comment]
When the view will be compiled, the JSON format will be cached in the compiled view. 
So it's completely static. Because of this, I don't think to filter certain translations on the back-end would be a good solution.
